---
abstract: 'Profile based data verification with Moose type constraints.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Verifier
requires:
  JSON::Any: 0
  JSON::XS: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Storage: 0
  MooseX::Storage::Deferred: 0
  Scalar::Util: 0
  Try::Tiny: 0
resources:
  repository: https://github.com/gphat/data-verifier
version: 0.45
